config/routes.rb
Am::Application.routes.draw do

  get "formatvideo/index"
  get "formatvideo/show"
  get "formatvideo/new"
  get "formatvideo/edit"
  get "formatvideo/create"
  get "formatvideo/update"
  get "formatvideo/destroy"

  resources :sessions, :only => [:new, :create, :destroy]

  resources :activities

  resources :video_clips

  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :video_clip_steps

  resources :password_resets

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    member { get :download }
  end

  match '/signin',                    :to     => 'sessions#new',              :via => 'get'
  match '/sessions',                  :to     => 'sessions#create',           :via => 'post'
  match '/sessions',                  :to     => 'sessions#new',              :via => 'get'
  match '/signout',                   :to     => 'sessions#destroy',          :via => 'delete'
  match '/management',                :to     => 'groups#management',         :via => 'get',     :as => :group_right_management

  match '/video_clips_unavailable',   :to => 'video_clips#indexUnavailable',  :via => 'get',     :as => :video_clips_unavailables

  match 'sendmail',                   :to     => 'sendvideos#index',          :via  => 'get',    :as => :sendmail
  match 'sendmail',                   :to     => 'sendvideos#create',         :via  => 'post',   :as => :send

  match 'logs/:lines',                :to     => 'logs#index',                :via  => 'get',    :as => :logs

  match 'activities/remove_all',      :to     => 'activities#remove_all',     :via  => 'post',   :as => :remove_all

  root 'sessions#new'

end

app/controllers/sendvideos_controller.rb
class SendvideosController < ApplicationController

  def index
    @groups = Group.search(params[:q])
    @people = Person.search(params[:q])
    @video_clips = VideoClip.search(params[:q])
  end


  def create
    mails = Array.new
    videosUrl = Array.new
    subject = params[:subject]
    groups = params[:groups_tokens]
    users = params[:users_tokens]
    videos = params[:videos_tokens]
    message = params[:message_email]
    mails = getMails(groups, users, mails)
    videosUrl = getVideoUrl(videos, videosUrl)
    mails.each do |mail|
      PersonMailer.send_video(subject, mail, videosUrl, message).deliver
    end
  end

  private
    def getVideoUrl(videos, videosUrl)
      videos_list = getElementArray(videos)
      if !(videos_list.nil?)
        videos_list.each do |video|
          videoActiveRecord = VideoClip.find_by_id(video.lstrip.to_i)
          if videoActiveRecord.videoclip_from_url.empty?
            videosUrl << videoActiveRecord.videoitemclip.url
          else
            videosUrl << videoActiveRecord.videoclip_from_url
          end
        end
      end
      return videosUrl
    end

    def getMails(groups, users, mails)
      mails = getGroupsMails(groups, mails)
      mails = getUsersMails(users, mails)
      mails = mails.uniq
      return mails
    end

    def getUsersMails(users, mails)
      users_list = getElementArray(users)
      if !(users_list.nil?)
        users_list.each do |user|
          userActiveRecord = Person.find_by_id(user.lstrip.to_i)
          mails << userActiveRecord.email
        end
      end
      return mails
    end

    def getGroupsMails(groups, mails)
      groups_list = getElementArray(groups)
      if !(groups_list.nil?)
        groups_list.each do |group|
          groupActiveRecord = Group.find_by_id(group.lstrip.to_i)
          groupActiveRecord.people.each do |user|
            userActiveRecord = Person.find(user)
            mails << userActiveRecord.email
          end
        end
      end
      return mails
    end

    def getElementArray(elements)
      if !(elements.empty?)
        return elements.split(',')
      end
      return nil
    end

end

app/helpers/sendvideos_helper.rb
module SendvideosHelper
end

app/views/sendvideos/create.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1><%= t('sendmail.confirmation_title') %>  <small><%= t('sendmail.confirmation_description') %></small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i> <%= t('sendmail.confirmation_title') %> </li>
      </ol>
    </div>
  </div>

  <p>
    <%= t('sendmail.message') %>
  </p>

</div>

app/views/sendvideos/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1><%= t('sendmail.title') %> <small><%= t('sendmail.description') %></small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i> <%= t('sendmail.title') %> </li>
      </ol>
    </div>
  </div>

  <div class="row">
    <div class="col-md-5">
      <%= form_for send_path :method => 'post'  do %>
          <p>
            <%= text_field_tag :subject, params[:subject], :size => 47, :autocomplete => :off, :placeholder => t('sendmail.subject'), class:'form-control' %>
          </p>
          <p>
            <%= label_tag :groups_tokens, t('group.title') %>
            <%= text_field_tag :groups_tokens, "data-pre" => @groups.map(&:attributes).to_json %>
            <%= label_tag :users_tokens, t('person.title') %><br>
            <%= text_field_tag :users_tokens, "data-pre" => @people.map(&:attributes).to_json %>
            <%= label_tag :videos_tokens, t('video_clip.videos_label') %><br>
            <%= text_field_tag :videos_tokens, "data-pre" => @video_clips.map(&:attributes).to_json %>
            <%= label_tag :message_email, t('comment.message') %>:<br />
            <%= text_area_tag :message_email, nil, :cols => 46, :rows => 3, class:'form-control' %>
          </p>
          <p>
            <%= submit_tag t('sendmail.send'), class: 'btn btn-large btn-primary'%>
          </p>
        <% end %>
    </div>
  </div>
</div>

<script>
    $(function() {
        $('#groups_tokens').tokenInput('/groups.json', {
            crossDomain: false,
            prePopulate: $('#groups_tokens').data('pre'),
            theme: 'facebook'
        });

        $('#users_tokens').tokenInput('/people.json', {
            propertyToSearch: 'name',
            crossDomain: false,
            prePopulate: $('#users_tokens').data('pre'),
            preventDuplicates: true,
            theme: 'facebook'
        });

        $('#videos_tokens').tokenInput('/video_clips.json', {
            propertyToSearch: 'title',
            hintText: 'Tape videos to send...',
            crossDomain: false,
            prePopulate: $('#videos_tokens').data('pre'),
            preventDuplicates: true,
            theme: 'facebook'
        });
    });
</script>