config/routes.rb
Am::Application.routes.draw do

  get "formatvideo/index"
  get "formatvideo/show"
  get "formatvideo/new"
  get "formatvideo/edit"
  get "formatvideo/create"
  get "formatvideo/update"
  get "formatvideo/destroy"

  resources :sessions, :only => [:new, :create, :destroy]

  resources :activities

  resources :video_clips

  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :video_clip_steps

  resources :password_resets

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    member { get :download }
  end

  match '/signin',                    :to     => 'sessions#new',              :via => 'get'
  match '/sessions',                  :to     => 'sessions#create',           :via => 'post'
  match '/sessions',                  :to     => 'sessions#new',              :via => 'get'
  match '/signout',                   :to     => 'sessions#destroy',          :via => 'delete'
  match '/management',                :to     => 'groups#management',         :via => 'get',     :as => :group_right_management

  match '/video_clips_unavailable',   :to => 'video_clips#indexUnavailable',  :via => 'get',     :as => :video_clips_unavailables

  match 'sendmail',                   :to     => 'sendvideos#index',          :via  => 'get',    :as => :sendmail
  match 'sendmail',                   :to     => 'sendvideos#create',         :via  => 'post',   :as => :send

  match 'logs/:lines',                :to     => 'logs#index',                :via  => 'get',    :as => :logs

  match 'activities/remove_all',      :to     => 'activities#remove_all',     :via  => 'post',   :as => :remove_all

  root 'sessions#new'

end

app/views/shared/_navigation.erb
<ul class="nav navbar-nav side-nav">
  <!-- <li><%#= link_to 'Videos', videoitems_path, :alt => 'videos' %></li> -->
  <% if current_person.type == Person::TYPES[0] %> <!-- TYPES[0] == Admin -->
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= t('nav.nagivation.videos') %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to t('nav.nagivation.allvideos') , video_clips_path, :alt => t('nav.nagivation.allvideos') %></li>
          <li><%= link_to t('nav.nagivation.videosunavailable'), video_clips_unavailables_path, :alt => t('nav.nagivation.videosunavailable') %></li>
        </ul>
      </li>
      <li><%= link_to t('nav.nagivation.rights'), rights_path, :alt => t('nav.nagivation.rights') %></li>
      <li><%= link_to t('nav.nagivation.groups'),  groups_path, :alt => t('nav.nagivation.groups') %></li>
      <li><%= link_to t('nav.nagivation.groupsrights'), group_right_management_path, :alt => t('nav.nagivation.groupsrights') %></li>
      <li><%= link_to t('nav.nagivation.users'), people_path,  :alt => t('nav.nagivation.users') %></li>
      <li><%= link_to t('nav.nagivation.sendmail'), sendmail_path,:alt => t('nav.nagivation.sendmail') %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown"> <%= t('nav.nagivation.logs') %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to t('nav.nagivation.logsystem'), logs_path(lines: 500), :alt => t('nav.nagivation.logsystem')  %></li>
          <li><%= link_to t('nav.nagivation.logactivities'), activities_path, :alt => t('nav.nagivation.logactivities') %></li>
        </ul>
      </li>
      <!-- AJOUTER PARTIE PATH -->
  <% else %>
      <li><%= link_to t('nav.nagivation.videos'), video_clips_path, :alt => t('nav.nagivation.videos') %></li>
  <% end %>

</ul>