config/routes.rb
Am::Application.routes.draw do

  get "formatvideo/index"
  get "formatvideo/show"
  get "formatvideo/new"
  get "formatvideo/edit"
  get "formatvideo/create"
  get "formatvideo/update"
  get "formatvideo/destroy"

  resources :sessions, :only => [:new, :create, :destroy]

  resources :activities

  resources :video_clips

  resources :people,        :controller => 'people',    :type => 'person'
  resources :admins,        :controller => 'people',    :type => 'admin'
  resources :users,         :controller => 'people',    :type => 'user'

  resources :personalgroups

  resources :video_clip_steps

  resources :password_resets

  resources :rights

  resources :groups

  resources :comments, :only => [:create, :index, :new]

  resources :videoitems do
      resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    resources :comments, :only => [:create, :index, :new]
  end

  resources :video_clips do
    member { get :download }
  end

  match '/signin',                    :to     => 'sessions#new',              :via => 'get'
  match '/sessions',                  :to     => 'sessions#create',           :via => 'post'
  match '/sessions',                  :to     => 'sessions#new',              :via => 'get'
  match '/signout',                   :to     => 'sessions#destroy',          :via => 'delete'
  match '/management',                :to     => 'groups#management',         :via => 'get',     :as => :group_right_management

  match '/video_clips_unavailable',   :to => 'video_clips#indexUnavailable',  :via => 'get',     :as => :video_clips_unavailables

  match 'sendmail',                   :to     => 'sendvideos#index',          :via  => 'get',    :as => :sendmail
  match 'sendmail',                   :to     => 'sendvideos#create',         :via  => 'post',   :as => :send

  match 'logs/:lines',                :to     => 'logs#index',                :via  => 'get',    :as => :logs

  match 'activities/remove_all',      :to     => 'activities#remove_all',     :via  => 'post',   :as => :remove_all

  root 'sessions#new'

end

app/models/right.rb
class Right < ActiveRecord::Base

  include PublicActivity::Model
  tracked except: :update, owner: ->(controller, model) { controller && controller.current_person }

  has_and_belongs_to_many :groups, :join_table => 'groups_rights'
    has_and_belongs_to_many :personalgroups, :join_table => 'personal_groupsrights'

    validates :name, presence: true
end

app/controllers/rights_controller.rb
class RightsController < ApplicationController
  before_action :set_right, only: [:show, :edit, :update, :destroy]
  before_filter :signed_in_person
  before_filter :verify_access


  # GET /rights
  # GET /rights.json
  def index
    @rights = Right.all
  end

  # GET /rights/1
  # GET /rights/1.json
  def show
  end

  # GET /rights/new
  def new
    @right = Right.new
  end

  # GET /rights/1/edit
  def edit
  end

  # POST /rights
  # POST /rights.json
  def create
    @right = Right.new(right_params)

    respond_to do |format|
      if @right.save
        format.html { redirect_to @right, notice: t('right.created_msg') }
        format.json { render action: 'show', status: :created, location: @right }
      else
        format.html { render action: 'new' }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rights/1
  # PATCH/PUT /rights/1.json
  def update
    respond_to do |format|
      if @right.update(right_params)
        format.html { redirect_to @right, notice: t('right.updated_msg') }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @right.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rights/1
  # DELETE /rights/1.json
  def destroy
    @right.destroy
    respond_to do |format|
      format.html { redirect_to rights_url }
      format.json { head :no_content }
    end
  end

  def signed_in_person
    redirect_to signin_path, notice: 'Please sign in.' unless signed_in?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_right
      @right = Right.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def right_params
      params.require(:right).permit(:name, :is_available)
    end

    def verify_access
      if !(current_person.nil?)
        if current_person.type != 'Admin'
          respond_to do |format|
            format.html { render :file => "#{Rails.root}/public/422.html", :status => :unprocessable_entity, :layout => false }
          end
        end
      else
        respond_to do |format|
          format.html { render :file => "#{Rails.root}/public/422.html", :status => :unprocessable_entity, :layout => false }
        end
      end
    end
end

app/helpers/rights_helper.rb
module RightsHelper
end

app/views/rights/_form.html.erb
<%= form_for(@right) do |f| %>
  <% if @right.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@right.errors.count, "error") %> prohibited this right from being saved:</h2>
      <ul>
      <% @right.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label t('name_label') %><br>
    <%= f.text_field :name, :placeholder => t('name_label'), :autocomplete => :off  %>
  </div>
  <div class="field">
    <%= f.label t('availability') %><br>
    <%= f.check_box :is_available %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rights/edit.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1><%= t('right.edit.title') %> <small><%= t('right.edit.description') %></small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  <%= t('right.edit.title') %> </li>
      </ol>
    </div>
  </div>

  <%= render 'form' %>

  <%= link_to t('action.show'), @right, class:'btn btn-default' %>
  <%= link_to t('action.back'), rights_path, class:'btn btn-default' %>
</div>

app/views/rights/index.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1> <%= t('right.title') %> <small><%= t('right.description') %></small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  <%= t('right.title') %> </li>
      </ol>
    </div>
  </div>

  <div>
    <div class="row">
      <div class="col-lg-6">
        <div class="table-responsive">
          <table class="table table-bordered table-hover table-striped tablesorter">
            <thead>
            <tr>
              <th><%= t('name_label') %><i class="fa fa-sort"></i></th>
              <th><%= t('availability') %> <i class="fa fa-sort"></i></th>
              <th><i class="fa fa-sort"></i></th>
              <th><i class="fa fa-sort"></i></th>
              <th><i class="fa fa-sort"></i></th>
            </tr>
            </thead>

            <tbody>
            <% @rights.each do |right| %>
                <tr>
                  <td><%= right.name %></td>
                  <td><%= right.is_available %></td>
                  <td><%= link_to t('action.show'), right %></td>
                  <td><%= link_to t('action.edit'), edit_right_path(right) %></td>
                  <td><%= link_to t('action.destroy'), right, method: :delete, data: { confirm: t('action.destroyconfirme') } %></td>
                </tr>
            <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div><!-- /.row -->
    <%= link_to t('right.new_right_label'), new_right_path, class:'btn btn-default' %>
  </div>
  <br>
</div>

app/views/rights/new.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1> <%= t('right.new.title') %> <small><%= t('right.new.description') %></small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i> <%= t('right.new.title') %> </li>
      </ol>
    </div>
  </div>

  <%= render 'form' %>
  <%= link_to t('action.back'), rights_path, class:'btn btn-default' %>
</div>

app/views/rights/show.html.erb
<div id="page-wrapper">
  <div class="row">
    <div class="col-lg-12">
      <h1> <%= t('right.show.title') %> <small> <%= t('right.show.description') %></small></h1>
      <ol class="breadcrumb">
        <li class="active"><i class="fa fa-dashboard"></i>  <%= t('right.show.title') %> </li>
      </ol>
    </div>
  </div>

  <p id="notice"><%= notice %></p>
  <p>
    <strong><%= t('name_label') %>:</strong>
    <%= @right.name %>
  </p>

  <p>
    <strong><%= t('availability') %>:</strong>
    <%= @right.is_available %>
  </p>

  <%= link_to t('action.edit'), edit_right_path(@right), class:'btn btn-default' %>
  <%= link_to t('action.back'), rights_path, class:'btn btn-default' %>

</div>